---
# tasks file for workstations
- name: What OS are we attempting to configure.
  ansible.builtin.debug:
    var: os

- name: What User are we using.
  ansible.builtin.debug:
    var: user
    
- import_tasks: install_Windows.yml
  when: os == "windows"

- import_tasks: install_Mac.yml
  when: os == "mac"

- import_tasks: install_Mojave.yml
  when: os == "mojave"
    